version: '3.1'

services:

  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: gitrev
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  script:
    depends_on:
      - db
    build:
      context: .
    env_file:
      - .env
    environment:
      - DATABASE_ADDRESS="db"
    volumes:
    - ./:/workspace:shared
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafanadata:/var/lib/grafana
volumes:
  pgdata:
  grafanadata: