"""Add user utc locale

Revision ID: 4479d18b570c
Revises: 8c8da54d4f67
Create Date: 2021-04-07 14:23:50.487379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4479d18b570c'
down_revision = '8c8da54d4f67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('utc_locale', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'utc_locale')
    # ### end Alembic commands ###
