"""Add repo relationship with PRs and Issues

Revision ID: 8725d76c32b9
Revises: 9264119891a2
Create Date: 2021-04-06 23:05:49.360495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8725d76c32b9'
down_revision = '9264119891a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('repository_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'issues', 'repositories', ['repository_id'], ['id'])
    op.add_column('pull_requests', sa.Column('repository_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pull_requests', 'repositories', ['repository_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pull_requests', type_='foreignkey')
    op.drop_column('pull_requests', 'repository_id')
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_column('issues', 'repository_id')
    # ### end Alembic commands ###
