"""Add user dates

Revision ID: 8c8da54d4f67
Revises: 8725d76c32b9
Create Date: 2021-04-07 08:29:53.205165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c8da54d4f67'
down_revision = '8725d76c32b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('issues_number_key', 'issues', type_='unique')
    op.drop_constraint('pull_requests_number_key', 'pull_requests', type_='unique')
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.create_unique_constraint('pull_requests_number_key', 'pull_requests', ['number'])
    op.create_unique_constraint('issues_number_key', 'issues', ['number'])
    # ### end Alembic commands ###
