"""Fix PR model

Revision ID: 9264119891a2
Revises: 8ee9cee08033
Create Date: 2021-04-06 22:10:08.484518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9264119891a2'
down_revision = '8ee9cee08033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pull_request_comments_pull_request_id_fkey', 'pull_request_comments', type_='foreignkey')
    op.create_foreign_key(None, 'pull_request_comments', 'pull_requests', ['pull_request_id'], ['id'])
    op.add_column('users', sa.Column('location', sa.String(), nullable=True))
    op.add_column('users', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'url')
    op.drop_column('users', 'location')
    op.drop_constraint(None, 'pull_request_comments', type_='foreignkey')
    op.create_foreign_key('pull_request_comments_pull_request_id_fkey', 'pull_request_comments', 'issues', ['pull_request_id'], ['id'])
    # ### end Alembic commands ###
